import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'tailwindcss/tailwind.css'
import { useEffect, useState } from 'react'


export default function Home() {

  const [data, setData] = useState([]);

  const fetchJson = () => {
    fetch('/data.json')
    .then(response => {
      return response.json();
    })
    .then(data => {
      setData(data);
    }).catch((e) => {
      console.log(e.message);
    });
  }

  useEffect(() => {
    fetchJson();
  },[]);
  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <div className='text-[red]'>ffdfdf</div>
      </main>
    </>
  )
}
